AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CloudSignalProcessFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
        Handler: lambda_function.lambda_handler
        Role: !GetAtt CloudSignalFunctionRole.Arn
        Runtime: python3.7
        Description: Cloud signal process function (Sequential Workload)
        CodeUri: /Users/elchoco/ms_cs/academics/2y/Thesis/mastergit/cloud/code/lambda/
        MemorySize: 512
        Timeout: 10
        Layers:
          - !Sub "arn:aws:lambda:aws-region:580247275435:layer:LambdaInsightsExtension:38"
          - !Sub arn:aws:lambda:aws-region:account-id:layer:numpy37:2
        Policies:
          - CloudWatchLambdaInsightsExecutionRolePolicy
  
  CloudSignalProcessConcurrentFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
        Handler: lambda_function.lambda_handler
        Role: !GetAtt CloudSignalFunctionRole.Arn
        Runtime: python3.7
        Description: Cloud signal process function (Concurrent Workload)
        CodeUri: /Users/elchoco/ms_cs/academics/2y/Thesis/mastergit/cloud/code/lambda/
        MemorySize: 512
        Timeout: 10
        Layers:
          - !Sub "arn:aws:lambda:aws-region:580247275435:layer:LambdaInsightsExtension:38"
          - !Sub arn:aws:lambda:aws-region:account-id:layer:numpy37:2
        Policies:
          - CloudWatchLambdaInsightsExecutionRolePolicy
  
  CloudSignalFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloud-signal-throughput-function-experiment-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 bucket permissions
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::cloud-signal-throughput-experiment
                  - arn:aws:s3:::cloud-signal-throughput-experiment/*
              # CloudWatch permissions
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

Outputs:
  CloudSignalProcessFunctionArn:
    Description: "Signal processing Lambda ARN"
    Value: !GetAtt CloudSignalProcessFunction.Arn
  CloudSignalProcessConcurrentFunctionArn:
    Description: "Signal processing concurrent Lambda ARN"
    Value: !GetAtt CloudSignalProcessConcurrentFunction.Arn