AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  SignalFunction:
    Type: AWS::Serverless::Application
    Properties:
      Location: signal_function.yaml

Outputs:
  CloudSignalProcessFunctionArn:
    Description: "Signal processing Lambda ARN"
    Value: !GetAtt SignalFunction.Outputs.CloudSignalProcessFunctionArn
  CloudSignalProcessConcurrentFunctionArn:
    Description: "Signal processing concurrent Lambda ARN"
    Value: !GetAtt SignalFunction.Outputs.CloudSignalProcessConcurrentFunctionArn