version = 0.1
[default.deploy.parameters]
stack_name = ""
resolve_s3 = true
s3_prefix = ""
region = ""
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = []
