AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  ExperimentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cloud-sorting-throughput-experiment
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  PlenseCloudTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cloud-signal-throughput-experiment
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  PlenseCloudTableArn:
    Description: "DynamoDB Table Arn"
    Value: !GetAtt PlenseCloudTable.Arn